name: Compile LaTeX document

on:
  push:
    branches:
      - main  # Change to your default branch if it's not 'main' [UNCHANGED]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: chapter.tex

    - name: Upload PDF file
      uses: actions/upload-artifact@v3
      with:
        name: PDF
        path: chapter.pdf

    - name: Commit and push PDF to repository
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add chapter.pdf
        git commit -m "Update compiled PDF"
        git push
